"""
Artifact Model - Tracks generated files and documents
"""

from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Text, BigInteger, Index, JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from datetime import datetime

from app.db.base import Base


# Use JSON type with JSONB for PostgreSQL (falls back to JSON for SQLite)
JSONType = JSON().with_variant(JSONB(), 'postgresql')


class Artifact(Base):
    """
    Artifact model for tracking generated files and documents.
    
    Each artifact represents a file generated by an agent, such as:
    - PDF reports
    - DOCX documents
    - Charts and visualizations (PNG, SVG, HTML)
    - Data exports (CSV, Excel)
    - Any other generated files
    
    Artifacts are:
    - Associated with tasks and users
    - Stored with metadata for retrieval
    - Downloadable via API
    - Tracked for lifecycle management
    """
    
    __tablename__ = "artifacts"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True)
    
    # Artifact identification
    artifact_id = Column(String(255), unique=True, nullable=False, index=True)
    
    # Task association (optional - artifact may exist without task)
    task_id = Column(Integer, ForeignKey("tasks.id", ondelete="SET NULL"), nullable=True, index=True)
    
    # User association
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Agent information
    agent_type = Column(String(50), nullable=False, index=True)
    
    # File information
    file_name = Column(String(255), nullable=False)
    file_type = Column(String(50), nullable=False)  # pdf, docx, png, svg, csv, etc
    file_path = Column(String(500), nullable=False)  # Storage path (local or cloud)
    file_size = Column(BigInteger, nullable=False)  # Size in bytes
    mime_type = Column(String(100), nullable=True)  # MIME type for proper serving
    
    # Metadata
    meta_data = Column(JSONType, nullable=True)  # Additional metadata (dimensions, pages, etc)
    
    # Lifecycle timestamps
    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow)
    
    # Relationships
    user = relationship("User", backref="artifacts")
    task = relationship("Task", backref="artifacts")
    
    # Composite indexes for common query patterns
    __table_args__ = (
        # Index for querying artifacts by user and agent (user's agent-specific artifacts)
        Index('idx_artifact_user_agent', 'user_id', 'agent_type'),
        # Index for querying artifacts by user and file type (filtering by type)
        Index('idx_artifact_user_filetype', 'user_id', 'file_type'),
        # Index for time-based queries (recent artifacts)
        Index('idx_artifact_created_at', 'created_at'),
    )
    
    def __repr__(self) -> str:
        return f"<Artifact(id={self.id}, artifact_id={self.artifact_id}, file_name={self.file_name}, user_id={self.user_id}, agent_type={self.agent_type})>"
    
    def to_dict(self) -> dict:
        """Convert artifact to dictionary"""
        return {
            "id": self.id,
            "artifact_id": self.artifact_id,
            "task_id": self.task_id,
            "user_id": self.user_id,
            "agent_type": self.agent_type,
            "file_name": self.file_name,
            "file_type": self.file_type,
            "file_path": self.file_path,
            "file_size": self.file_size,
            "mime_type": self.mime_type,
            "metadata": self.meta_data,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
